### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by aahnik** [smtchahal/url-shortener#5]
![image](https://user-images.githubusercontent.com/66209958/107794235-3015b280-6d7d-11eb-9155-c3f7f3a2f1a8.png)

Should I change the runtime.txt to the latest version of python ?

**Comment by smtchahal** [comment]
@aahnik Sure! Feel free to make a PR.

**Comment by aahnik** [comment]
changing python version is leading to tons of errors. I dont know if I am making any mistake.

Probably due to the fact that this repo uses very old version of all packages.
