### ISSUE TITLE
SIR PLEASE MAKE IT COMPATIBLE WITH RAILWAY.APP

### ISSUE THREAD

**Issue by ghost** [smtchahal/url-shortener#7]
App runs on railway.app but gives 400 bad request error please help

**Comment by smtchahal** [comment]
@Code-X-Mania I'm not familiar with railway.app, but the bad request suggests it might be a configuration/server issue. Could you post the stack trace you find? You'd need to turn debug mode on for that.

**Comment by ghost** [comment]
sir i have solved the issue it is working live on https://adarshgoel.cf

**Comment by smtchahal** [comment]
Great!
